In [1]:
# NB: The API key, secret, and ONHS user ID have been removed in this public version, rendering the code non-functional.
import flickrapi
import pandas as pd
import urllib.request
import time

In [2]:
api_key = ""
api_secret = ""
user_id = ''

In [3]:
flickr = flickrapi.FlickrAPI(api_key, api_secret, format='parsed-json')

In [4]:
# Pulling list of photosets uploaded by ONHS, limited to one page of results at a time
i = 3
while i:
    time.sleep(1)
    try:
        sets = flickr.photosets.getList(user_id=user_id, page=1)
    except:
        i -= 1
        continue
    else:
        break

In [5]:
# Getting the total number of pages
pages = sets['photosets']['pages']

In [6]:
# Converting results to DataFrame
picframe = pd.DataFrame(sets['photosets']['photoset'])

In [7]:
# Getting the rest of the pages
for j in range(2, (pages+1)):
    i = 3
    while i:
        time.sleep(1)
        try:
            sets = flickr.photosets.getList(user_id=user_id, page=j)
        except:
            i -= 1
            continue
        else:
            break
    if i == 0:
        print(f"Sets call for page {j} exceeded max tries")
        continue
    picframe = picframe.append(pd.DataFrame(sets['photosets']['photoset']), ignore_index=True, sort=False)

In [8]:
picframe.shape

(5829, 20)

In [19]:
# Taking a look at the structure
picframe.head()

,id,owner,username,primary,secret,server,farm,count_views,count_comments,count_photos,...,title,description,can_comment,date_create,date_update,photos,videos,visibility_can_see_set,needs_interstitial,JobNum
0,72157671158030953,79651136@N04,"Olmsted Archives, Frederick Law Olmsted NHS, NPS",29715248020,c58fd50161,8219,9,780,0,1,...,{'_content': 'Introduction'},{'_content': ''},0,1475173954,1598896699,1,0,1,0,None
1,72157644225984680,79651136@N04,"Olmsted Archives, Frederick Law Olmsted NHS, NPS",14189572143,4082c5df0e,7430,8,824,0,3,...,"{'_content': 'Job #1, Frederick Law Olmsted Sr...",{'_content': 'Please Credit: Courtesy of the N...,0,1399906216,1598896699,3,0,1,0,1
2,72157687887651586,79651136@N04,"Olmsted Archives, Frederick Law Olmsted NHS, NPS",36759142135,8d93236534,4345,5,372,0,331,...,"{'_content': 'Job #20, Olmsted Office, 99 Warr...",{'_content': ''},0,1503505690,1598896699,331,0,1,0,20
3,72157669529368582,79651136@N04,"Olmsted Archives, Frederick Law Olmsted NHS, NPS",27546385830,f86b5c1856,7316,8,176,0,23,...,"{'_content': 'Job #20, Miscellaneous General C...",{'_content': ''},0,1466608328,1598896699,23,0,1,0,20
4,72157649672827815,79651136@N04,"Olmsted Archives, Frederick Law Olmsted NHS, NPS",15791526009,652de9d05e,8648,9,368,0,3,...,"{'_content': 'Job #20, Olmsted Firm Family Tre...",{'_content': 'Please Credit: Courtesy of the N...,0,1418064411,1598896699,3,0,1,0,20

In [10]:
# Use known formatting scheme of titles to extract Olmsted firm job number
picframe['JobNum'] = [title['_content'].split(',')[0].split('#')[1].strip() if title['_content'].find('Job') != -1 else "None" for title in picframe['title']]

In [11]:
# Filter to get set IDs of desired job numbers
setIDs = picframe['id'][
    (picframe['JobNum'] == '290') | 
    (picframe['JobNum'] == '296') | 
    (picframe['JobNum'] == '297') | 
    (picframe['JobNum'] == '330') | 
    (picframe['JobNum'] == '623') | 
    (picframe['JobNum'] == '676') | 
    (picframe['JobNum'] == '1242') | 
    (picframe['JobNum'] == '1327') | 
    (picframe['JobNum'] == '1341') | 
    (picframe['JobNum'] == '2260') | 
    (picframe['JobNum'] == '2379') | 
    (picframe['JobNum'] == '2820') | 
    (picframe['JobNum'] == '2821') | 
    (picframe['JobNum'] == '2822') | 
    (picframe['JobNum'] == '2823') | 
    (picframe['JobNum'] == '2824') | 
    (picframe['JobNum'] == '2825') | 
    (picframe['JobNum'] == '2826') | 
    (picframe['JobNum'] == '2827') | 
    (picframe['JobNum'] == '2828') | 
    (picframe['JobNum'] == '2829') | 
    (picframe['JobNum'] == '2830') | 
    (picframe['JobNum'] == '2831') | 
    (picframe['JobNum'] == '2832') | 
    (picframe['JobNum'] == '2833') | 
    (picframe['JobNum'] == '2834') | 
    (picframe['JobNum'] == '2835') | 
    (picframe['JobNum'] == '2836') | 
    (picframe['JobNum'] == '2837') | 
    (picframe['JobNum'] == '2838') | 
    (picframe['JobNum'] == '2839') | 
    (picframe['JobNum'] == '2840') | 
    (picframe['JobNum'] == '2841') | 
    (picframe['JobNum'] == '2842') | 
    (picframe['JobNum'] == '2843') |
    (picframe['JobNum'] == '2844') | 
    (picframe['JobNum'] == '2845') |
    (picframe['JobNum'] == '2846') |
    (picframe['JobNum'] == '2847') |
    (picframe['JobNum'] == '2848') |
    (picframe['JobNum'] == '2849') |
    (picframe['JobNum'] == '2901') |
    (picframe['JobNum'] == '2914') |
    (picframe['JobNum'] == '2922') |
    (picframe['JobNum'] == '2931') |
    (picframe['JobNum'] == '2956') |
    (picframe['JobNum'] == '2961') |
    (picframe['JobNum'] == '2961') |
    (picframe['JobNum'] == '2964') |
    (picframe['JobNum'] == '2966') |
    (picframe['JobNum'] == '3035') |
    (picframe['JobNum'] == '3086') |
    (picframe['JobNum'] == '3297') |
    (picframe['JobNum'] == '3346') |
    (picframe['JobNum'] == '3358') |
    (picframe['JobNum'] == '3604') |
    (picframe['JobNum'] == '3643') |
    (picframe['JobNum'] == '3706') |
    (picframe['JobNum'] == '3749') |
    (picframe['JobNum'] == '5358') |
    (picframe['JobNum'] == '5518') |
    (picframe['JobNum'] == '5507') |
    (picframe['JobNum'] == '6487') |
    (picframe['JobNum'] == '6570') |
    (picframe['JobNum'] == '6574') |
    (picframe['JobNum'] == '6790') |
    (picframe['JobNum'] == '7002') |
    (picframe['JobNum'] == '7022') |
    (picframe['JobNum'] == '7054') |
    (picframe['JobNum'] == '7290') |
    (picframe['JobNum'] == '7308') |
    (picframe['JobNum'] == '7458') |
    (picframe['JobNum'] == '7714') |
    (picframe['JobNum'] == '7956') |
    (picframe['JobNum'] == '9299') |
    (picframe['JobNum'] == '9300') |
    (picframe['JobNum'] == '9451') |
    (picframe['JobNum'] == '9970') |
    (picframe['JobNum'] == '9992') |
    (picframe['JobNum'] == '12034') |
    (picframe['JobNum'] == '12044')
]

In [93]:
# Iterate through relevant set IDs, harvest number of total available plans from description, and compare with image count of set.
# NB: Output is in csv format but simply printed rather than saved to a csv
print("Job Number, Total Plans, Image Count, Discrepancy")
for setID in setIDs:
    description = picframe.loc[picframe['id'] == setID, 'description'].values[0]['_content'].lower()
    pic_count = picframe.loc[picframe['id'] == setID, 'count_photos'].values[0]
    job_num = picframe.loc[picframe['id'] == setID, 'JobNum'].values[0]
    location = description.find("total plans: ")
    if location != -1:
        parts = description[location+13:].split(" ")
        total_plans = parts[0]
        discrepancy = int(total_plans) - pic_count
        print(job_num + ", " + total_plans + ", " + str(pic_count) + ", " + str(discrepancy))

Job Number, Total Plans, Image Count, Discrepancy
296, 9, 7, 2
297, 11, 10, 1
623, 10, 9, 1
676, 4, 2, 2
1327, 23, 12, 11
1341, 7, 6, 1
2379, 1, 1, 0
2820, 207, 171, 36
2822, 51, 51, 0
2823, 13, 4, 9
2825, 2, 2, 0
2826, 16, 18, -2
2827, 3, 5, -2
2834, 2, 1, 1
2837, 113, 91, 22
2838, 15, 4, 11
2840, 42, 42, 0
2842, 5, 5, 0
2843, 888, 559, 329
2844, 91, 79, 12
2847, 19, 2, 17
2901, 106, 92, 14
2956, 4, 2, 2
2966, 9, 6, 3
3297, 343, 186, 157
3643, 3, 1, 2
3706, 4, 5, -1
5507, 6, 5, 1
6487, 135, 78, 57
6570, 218, 196, 22
6574, 12, 1, 11
6790, 10, 7, 3
7022, 4, 7, -3
7308, 11, 11, 0
7458, 177, 93, 84
7956, 71, 64, 7
9300, 8, 8, 0
9970, 2084, 2108, -24
9992, 258, 260, -2
12044, 7, 5, 2